site_name: Datalake DCIS
use_directory_urls: false
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material  # Specifies the theme to be used, here it's "Material" for MkDoc.
  language: en  # Sets the default language for the theme. Here, it's English.
  palette:
    primary: custom  # Indicates that a custom primary color will be used in the palette.
  logo: assets/images/inr_logo_blanc.png  # Path to the custom logo to display in the header.
  features:
    - navigation.expand  # Enables the feature to expand navigation menus in the sidebar.


markdown_extensions:
  - admonition  # Blocs spéciaux pour les notes, avertissements, etc.
  - abbr  # Gestion des abréviations avec infobulles explicatives
  - attr_list  # Ajout d'attributs personnalisés aux éléments Markdown
  - def_list  # Création de listes de définitions
  - footnotes  # Insertion de notes de bas de page
#  - meta  # Métadonnées au début des fichiers Markdown
  - md_in_html  # Permet l'utilisation de Markdown à l'intérieur du HTML
  - tables  # Améliore le rendu et les fonctionnalités des tableaux
  - toc:
      permalink: true  # Génère une table des matières avec des liens permanents
  - pymdownx.snippets  # Inclusion de fragments de code externes
  - pymdownx.details  # Blocs repliables pour masquer ou afficher du contenu
  - pymdownx.magiclink  # Conversion automatique des URLs en liens
  - pymdownx.tabbed  # Création d'onglets dans le contenu
  - pymdownx.betterem:
      smart_enable: all  # Amélioration de la détection des emphases (italique, gras)
  - pymdownx.critic  # Gestion des révisions et suggestions dans le texte
  - pymdownx.keys  # Affichage stylisé des touches de clavier
  - pymdownx.caret  # Support pour le texte en exposant
  - pymdownx.mark  # Mise en surbrillance du texte
  - pymdownx.tilde  # Support pour le texte en indice
  - pymdownx.highlight  # Mise en évidence du code avec coloration syntaxique
  - pymdownx.superfences  # Gestion avancée des blocs de code
  - pymdownx.inlinehilite  # Coloration syntaxique pour le code en ligne
  - pymdownx.smartsymbols  # Conversion automatique de symboles typographiques
  - pymdownx.arithmatex:
      generic: true  # Rendu des expressions mathématiques avec MathJax ou KaTeX
  - pymdownx.tasklist:
      custom_checkbox: true  # Listes de tâches avec cases à cocher personnalisées

extra_css:
  - stylesheets/extra.css # Ajout d'ombre autour des images

plugins:
  - search:
      lang:
        - en
        - fr  # Plugin de recherche avec support pour l'anglais et le français
  - awesome-pages  # Organisation avancée des pages
  - macros  # Définition et utilisation de macros
  - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: auto
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
        auto_caption: false
        caption_position: bottom

  - page-to-pdf:
      disableOnServe: true
      displayHeaderFooter: true
      printBackground: true
#      exclude:
#        - "index.*"