site_name: Datalake DCIS
use_directory_urls: false
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
  # custom_dir: custom/ si on custemise l'affichage cf. Benoit
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - meta
  - toc:
      permalink: true
#  - pymdownx.snippets
#  - pymdownx.details
#  - pymdownx.magiclink
#  - pymdownx.tabbed
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.mark
#  - pymdownx.tilde
#  - pymdownx.highlight
#  - pymdownx.superfences
#  - pymdownx.inlinehilite
#  - pymdownx.keys
#  - pymdownx.smartsymbols
#  - pymdownx.arithmatex:
#      generic: true
#  - pymdownx.tasklist:
#      custom_checkbox: true
plugins:
  - search:
      lang:
        - en
        - fr

  - awesome-pages
  - macros
#  - page-to-pdf:
#      disableOnServe: true
#      displayHeaderFooter: true
#      printBackground: true
##      exclude:
##        - "index.*"